version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata: